name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        ./buildDockerImage.sh -v 18.4.0 -x
        docker tag oracle/database:18.4.0-xe mayankbansal0105/database:18.4.0
         docker login -u mayankbansal0105 -p 5Vnzur_276332
         docker push mayankbansal0105/database:18.4.0
