name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build OracleDatabase/SingleInstance/dockerfiles/18.3.0/Dockerfile --file Dockerfile --tag my-image-name:$(date +%s)
