name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ls -ltrh && cd OracleDatabase/SingleInstance/dockerfiles/18.4.0 && docker build . --file Dockerfile.xe --tag my-image-name:$(date +%s)
